using System.Reflection;
using System.Security.Cryptography;
using System.Text.Json;

namespace Batcomputer;

/// <summary>Records packaged files, hashes, and preflight results for a completed build.</summary>
public sealed class BuildManifestService
{
    public sealed record Entry(string Package, string Role, string Ownership, string File, string Sha256, long Size);
    public sealed record Trio(string File, string Sha256, long Size);

    public sealed class Manifest
    {
        public int ManifestVersion { get; init; } = 1;
        public string BuildId { get; init; } = "";
        public string BuiltUtc { get; init; } = "";
        public string ToolVersion { get; init; } = "";
        public string GameBuild { get; init; } = "";
        public string SlotId { get; init; } = "";
        public string DisplayName { get; init; } = "";
        public string PackageBaseName { get; init; } = "";
        public string ModFolder { get; init; } = "";
        public Dictionary<string, string> DeclaredPackages { get; init; } = new();
        public List<Entry> ShippedPackages { get; init; } = new();
        public List<Trio> TrioFiles { get; init; } = new();
        public Dictionary<string, List<string>> Validation { get; init; } = new();
    }

    /// <summary>
    /// Builds and writes the manifest for a completed build. Returns the manifest (for logging) and
    /// the path it was written to. <paramref name="buildId"/> is generated by the caller so the same
    /// id can be stamped into the runtime suit.json - keeping the pak and its manifest cross-referenced.
    /// </summary>
    public (Manifest Manifest, string Path) Write(
        string buildId,
        string contentRootPacked,
        string modFolder,
        string ioStoreDir,
        string packageBaseName,
        string slotId,
        string displayName,
        IReadOnlyDictionary<string, string> declaredPackages,
        IReadOnlyList<string> validationErrors,
        IReadOnlyList<string> validationWarnings)
    {
        var declaredLeaves = declaredPackages.ToDictionary(
            kv => LeafOf(kv.Value),
            kv => kv.Key,
            StringComparer.OrdinalIgnoreCase);

        var shipped = new List<Entry>();
        var modContentRoot = string.IsNullOrWhiteSpace(modFolder)
            ? null
            : Path.Combine(contentRootPacked, "Mods", modFolder);

        if (modContentRoot is not null && Directory.Exists(modContentRoot))
        {
            foreach (var uasset in Directory.EnumerateFiles(modContentRoot, "*.uasset", SearchOption.AllDirectories)
                         .OrderBy(p => p, StringComparer.OrdinalIgnoreCase))
            {
                var leaf = Path.GetFileNameWithoutExtension(uasset);
                var pkg = FilePathToPackagePath(contentRootPacked, uasset);
                var role = declaredLeaves.TryGetValue(leaf, out var declaredRole)
                    ? declaredRole
                    : RoleFromLeaf(leaf);
                var (sha, size) = HashFile(uasset);
                shipped.Add(new Entry(pkg, role, "shipped", RelPath(ioStoreDir, uasset), sha, size));
            }
        }

        var trio = new List<Trio>();
        foreach (var ext in new[] { ".pak", ".ucas", ".utoc" })
        {
            var file = Path.Combine(ioStoreDir, packageBaseName + ext);
            if (File.Exists(file))
            {
                var (sha, size) = HashFile(file);
                trio.Add(new Trio(Path.GetFileName(file), sha, size));
            }
        }

        var manifest = new Manifest
        {
            BuildId = buildId,
            BuiltUtc = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ"),
            ToolVersion = ToolVersion(),
            GameBuild = SafeGameBuild(),
            SlotId = slotId,
            DisplayName = displayName,
            PackageBaseName = packageBaseName,
            ModFolder = modFolder,
            DeclaredPackages = declaredPackages.ToDictionary(kv => kv.Key, kv => kv.Value),
            ShippedPackages = shipped,
            TrioFiles = trio,
            Validation = new Dictionary<string, List<string>>
            {
                ["errors"] = validationErrors.ToList(),
                ["warnings"] = validationWarnings.ToList()
            }
        };

        Directory.CreateDirectory(ioStoreDir);
        var path = Path.Combine(ioStoreDir, "build-manifest.json");
        File.WriteAllText(path, JsonSerializer.Serialize(manifest, new JsonSerializerOptions
        {
            WriteIndented = true
        }));
        return (manifest, path);
    }

    /// <summary>
    /// Returns every expected package output that is absent or empty. Callers that delete the
    /// exact prior outputs before invoking retoc can use an empty result as the minimum proof that
    /// the current attempt produced a fresh complete trio.
    /// </summary>
    internal static List<string> FindMissingOrEmptyFiles(IEnumerable<string> expectedPaths) =>
        expectedPaths
            .Where(path => !File.Exists(path) || new FileInfo(path).Length == 0)
            .ToList();

    /// <summary>
    /// Verifies that an in-memory successful build result still names the exact trio written for
    /// that build ID. Call this immediately before install so an older or subsequently replaced
    /// trio cannot be copied merely because files happen to exist in the output directory.
    /// </summary>
    public bool VerifyInstallableTrio(
        Manifest manifest,
        string expectedBuildId,
        string expectedSlotId,
        string expectedPackageBaseName,
        string ioStoreDir,
        out string error)
    {
        if (string.IsNullOrWhiteSpace(expectedBuildId) ||
            !string.Equals(manifest.BuildId, expectedBuildId, StringComparison.Ordinal))
        {
            error = "The build manifest does not belong to this package attempt.";
            return false;
        }
        if (!string.Equals(manifest.SlotId, expectedSlotId, StringComparison.OrdinalIgnoreCase) ||
            !string.Equals(manifest.PackageBaseName, expectedPackageBaseName, StringComparison.OrdinalIgnoreCase))
        {
            error = "The build manifest belongs to a different suit or package name.";
            return false;
        }
        if (manifest.Validation.TryGetValue("errors", out var validationErrors) && validationErrors.Count > 0)
        {
            error = "The build manifest contains release-blocking validation errors.";
            return false;
        }

        var expectedNames = new[] { ".pak", ".ucas", ".utoc" }
            .Select(extension => expectedPackageBaseName + extension)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (manifest.TrioFiles.Count != expectedNames.Count ||
            manifest.TrioFiles.Any(entry =>
                !Path.GetFileName(entry.File).Equals(entry.File, StringComparison.Ordinal) ||
                !expectedNames.Contains(entry.File)) ||
            manifest.TrioFiles.Select(entry => entry.File).Distinct(StringComparer.OrdinalIgnoreCase).Count() != expectedNames.Count)
        {
            error = "The build manifest does not certify exactly one .pak, .ucas, and .utoc for this package.";
            return false;
        }

        var outputRoot = Path.GetFullPath(ioStoreDir)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        foreach (var entry in manifest.TrioFiles)
        {
            var file = Path.GetFullPath(Path.Combine(outputRoot, entry.File));
            if (!FileSystemPathUtil.IsWithinDirectory(file, outputRoot))
            {
                error = $"The certified trio path escapes its output directory: {entry.File}";
                return false;
            }
            if (!File.Exists(file))
            {
                error = $"The freshly built trio file is missing: {entry.File}";
                return false;
            }

            var (sha256, size) = HashFile(file);
            if (size != entry.Size || !sha256.Equals(entry.Sha256, StringComparison.OrdinalIgnoreCase))
            {
                error = $"The freshly built trio file changed after packaging: {entry.File}";
                return false;
            }
        }

        error = "";
        return true;
    }

    private static string RoleFromLeaf(string leaf)
    {
        if (leaf.StartsWith("MI_", StringComparison.OrdinalIgnoreCase) ||
            leaf.StartsWith("M_", StringComparison.OrdinalIgnoreCase)) return "material";
        if (leaf.StartsWith("T_", StringComparison.OrdinalIgnoreCase)) return "texture";
        if (leaf.StartsWith("SM_", StringComparison.OrdinalIgnoreCase) ||
            leaf.StartsWith("SK_", StringComparison.OrdinalIgnoreCase)) return "mesh";
        if (leaf.StartsWith("LAS_", StringComparison.OrdinalIgnoreCase) ||
            leaf.StartsWith("MAS_", StringComparison.OrdinalIgnoreCase)) return "animset";
        if (leaf.Contains("Archetype", StringComparison.OrdinalIgnoreCase)) return "archetype";
        if (leaf.Contains("DPRD", StringComparison.OrdinalIgnoreCase)) return "dprd";
        if (leaf.Contains("DCMD", StringComparison.OrdinalIgnoreCase)) return "dcmd";
        if (leaf.Contains("UIMD", StringComparison.OrdinalIgnoreCase) ||
            leaf.Contains("UIMetaData", StringComparison.OrdinalIgnoreCase)) return "uimd";
        return "other";
    }

    private static string LeafOf(string packagePath)
    {
        var norm = packagePath.Contains('.') ? packagePath[..packagePath.IndexOf('.')] : packagePath;
        var slash = norm.LastIndexOf('/');
        return slash >= 0 ? norm[(slash + 1)..] : norm;
    }

    private static string FilePathToPackagePath(string contentRoot, string uassetPath)
    {
        var rel = Path.GetRelativePath(contentRoot, Path.ChangeExtension(uassetPath, null))
            .Replace(Path.DirectorySeparatorChar, '/');
        return "/Game/" + rel;
    }

    private static string RelPath(string fromDir, string file)
    {
        try { return Path.GetRelativePath(fromDir, file).Replace(Path.DirectorySeparatorChar, '/'); }
        catch { return Path.GetFileName(file); }
    }

    private static (string Sha, long Size) HashFile(string path)
    {
        using var stream = File.OpenRead(path);
        using var sha = SHA256.Create();
        var hash = sha.ComputeHash(stream);
        return (Convert.ToHexString(hash).ToLowerInvariant(), new FileInfo(path).Length);
    }

    private static string ToolVersion()
    {
        var asm = Assembly.GetExecutingAssembly();
        return asm.GetName().Version?.ToString()
            ?? asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
            ?? "0.0.0";
    }

    private static string SafeGameBuild()
    {
        try { return GameDataService.Instance.Db.GameBuild; }
        catch { return ""; }
    }
}
