using System.Reflection;
using System.Security.Cryptography;
using System.Text.Json;

namespace Batcomputer;

/// <summary>
/// Phase 2 (unified workspace & collector): after a suit packages successfully, this writes a
/// <c>build-manifest.json</c> beside the IoStore trio. The manifest is the durable record of
/// exactly WHAT shipped in a build:
///   * an immutable <c>build_id</c> (fresh per successful package) + UTC timestamp + tool/game build
///   * every package file bundled into the pak, with role + ownership + SHA-256 (the dependency
///     inventory / ownership map - Phase 2 items 2 & 3)
///   * the trio (.pak/.ucas/.utoc) hashes so a build can be verified byte-identical later
///   * the preflight validation report (errors/warnings) that gated the build
/// It reads only the already-staged files and never mutates anything - safe to call post-package.
/// </summary>
public sealed class BuildManifestService
{
    public sealed record Entry(string Package, string Role, string Ownership, string File, string Sha256, long Size);
    public sealed record Trio(string File, string Sha256, long Size);

    public sealed class Manifest
    {
        public int ManifestVersion { get; init; } = 1;
        public string BuildId { get; init; } = "";
        public string BuiltUtc { get; init; } = "";
        public string ToolVersion { get; init; } = "";
        public string GameBuild { get; init; } = "";
        public string SlotId { get; init; } = "";
        public string DisplayName { get; init; } = "";
        public string PackageBaseName { get; init; } = "";
        public string ModFolder { get; init; } = "";
        public Dictionary<string, string> DeclaredPackages { get; init; } = new();
        public List<Entry> ShippedPackages { get; init; } = new();
        public List<Trio> TrioFiles { get; init; } = new();
        public Dictionary<string, List<string>> Validation { get; init; } = new();
    }

    /// <summary>
    /// Builds and writes the manifest for a completed build. Returns the manifest (for logging) and
    /// the path it was written to. <paramref name="buildId"/> is generated by the caller so the same
    /// id can be stamped into the runtime suit.json - keeping the pak and its manifest cross-referenced.
    /// </summary>
    public (Manifest Manifest, string Path) Write(
        string buildId,
        string contentRootPacked,
        string modFolder,
        string ioStoreDir,
        string packageBaseName,
        string slotId,
        string displayName,
        IReadOnlyDictionary<string, string> declaredPackages,
        IReadOnlyList<string> validationErrors,
        IReadOnlyList<string> validationWarnings)
    {
        var declaredLeaves = declaredPackages.ToDictionary(
            kv => LeafOf(kv.Value),
            kv => kv.Key,
            StringComparer.OrdinalIgnoreCase);

        var shipped = new List<Entry>();
        var modContentRoot = string.IsNullOrWhiteSpace(modFolder)
            ? null
            : Path.Combine(contentRootPacked, "Mods", modFolder);

        if (modContentRoot is not null && Directory.Exists(modContentRoot))
        {
            foreach (var uasset in Directory.EnumerateFiles(modContentRoot, "*.uasset", SearchOption.AllDirectories)
                         .OrderBy(p => p, StringComparer.OrdinalIgnoreCase))
            {
                var leaf = Path.GetFileNameWithoutExtension(uasset);
                var pkg = FilePathToPackagePath(contentRootPacked, uasset);
                var role = declaredLeaves.TryGetValue(leaf, out var declaredRole)
                    ? declaredRole
                    : RoleFromLeaf(leaf);
                var (sha, size) = HashFile(uasset);
                shipped.Add(new Entry(pkg, role, "shipped", RelPath(ioStoreDir, uasset), sha, size));
            }
        }

        var trio = new List<Trio>();
        foreach (var ext in new[] { ".pak", ".ucas", ".utoc" })
        {
            var file = Path.Combine(ioStoreDir, packageBaseName + ext);
            if (File.Exists(file))
            {
                var (sha, size) = HashFile(file);
                trio.Add(new Trio(Path.GetFileName(file), sha, size));
            }
        }

        var manifest = new Manifest
        {
            BuildId = buildId,
            BuiltUtc = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ"),
            ToolVersion = ToolVersion(),
            GameBuild = SafeGameBuild(),
            SlotId = slotId,
            DisplayName = displayName,
            PackageBaseName = packageBaseName,
            ModFolder = modFolder,
            DeclaredPackages = declaredPackages.ToDictionary(kv => kv.Key, kv => kv.Value),
            ShippedPackages = shipped,
            TrioFiles = trio,
            Validation = new Dictionary<string, List<string>>
            {
                ["errors"] = validationErrors.ToList(),
                ["warnings"] = validationWarnings.ToList()
            }
        };

        Directory.CreateDirectory(ioStoreDir);
        var path = Path.Combine(ioStoreDir, "build-manifest.json");
        File.WriteAllText(path, JsonSerializer.Serialize(manifest, new JsonSerializerOptions
        {
            WriteIndented = true
        }));
        return (manifest, path);
    }

    private static string RoleFromLeaf(string leaf)
    {
        if (leaf.StartsWith("MI_", StringComparison.OrdinalIgnoreCase) ||
            leaf.StartsWith("M_", StringComparison.OrdinalIgnoreCase)) return "material";
        if (leaf.StartsWith("T_", StringComparison.OrdinalIgnoreCase)) return "texture";
        if (leaf.StartsWith("SM_", StringComparison.OrdinalIgnoreCase) ||
            leaf.StartsWith("SK_", StringComparison.OrdinalIgnoreCase)) return "mesh";
        if (leaf.StartsWith("LAS_", StringComparison.OrdinalIgnoreCase) ||
            leaf.StartsWith("MAS_", StringComparison.OrdinalIgnoreCase)) return "animset";
        if (leaf.Contains("Archetype", StringComparison.OrdinalIgnoreCase)) return "archetype";
        if (leaf.Contains("DPRD", StringComparison.OrdinalIgnoreCase)) return "dprd";
        if (leaf.Contains("DCMD", StringComparison.OrdinalIgnoreCase)) return "dcmd";
        if (leaf.Contains("UIMD", StringComparison.OrdinalIgnoreCase) ||
            leaf.Contains("UIMetaData", StringComparison.OrdinalIgnoreCase)) return "uimd";
        return "other";
    }

    private static string LeafOf(string packagePath)
    {
        var norm = packagePath.Contains('.') ? packagePath[..packagePath.IndexOf('.')] : packagePath;
        var slash = norm.LastIndexOf('/');
        return slash >= 0 ? norm[(slash + 1)..] : norm;
    }

    private static string FilePathToPackagePath(string contentRoot, string uassetPath)
    {
        var rel = Path.GetRelativePath(contentRoot, Path.ChangeExtension(uassetPath, null))
            .Replace(Path.DirectorySeparatorChar, '/');
        return "/Game/" + rel;
    }

    private static string RelPath(string fromDir, string file)
    {
        try { return Path.GetRelativePath(fromDir, file).Replace(Path.DirectorySeparatorChar, '/'); }
        catch { return Path.GetFileName(file); }
    }

    private static (string Sha, long Size) HashFile(string path)
    {
        using var stream = File.OpenRead(path);
        using var sha = SHA256.Create();
        var hash = sha.ComputeHash(stream);
        return (Convert.ToHexString(hash).ToLowerInvariant(), new FileInfo(path).Length);
    }

    private static string ToolVersion()
    {
        var asm = Assembly.GetExecutingAssembly();
        return asm.GetName().Version?.ToString()
            ?? asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
            ?? "0.0.0";
    }

    private static string SafeGameBuild()
    {
        try { return GameDataService.Instance.Db.GameBuild; }
        catch { return ""; }
    }
}
