using System.Diagnostics;
using System.Text.Json;

namespace Batcomputer;

/// <summary>
/// Produces the small, cooked AssetRegistry plugin that tells the game about every
/// enabled mod DCMD during startup. The actual binary is deliberately written by
/// the verified UE 5.6 commandlet; Batcomputer owns layout, invocation, and the
/// release-facing verification contract.
/// </summary>
public sealed class RegistryPluginService
{
    public const string PrimaryAssetType = "PawnMetaData";
    public const string PawnMetadataClass = "/Script/DinnerPawnMetaData.DinnerCharacterMetaData";
    public const string WriterResultMarker = "SUIT_SLOTS_REGISTRY_WRITER_RESULT";
    private const string ProofSentinelRoot = "/Game/Developers/NstDevScan";

    public sealed record RegistryRow(string PackagePath)
    {
        public string AssetName => UnrealPathUtil.AssetName(PackagePath);
    }

    public sealed record PluginLayout(
        string PluginName,
        string PluginDirectory,
        string DescriptorPath,
        string RegistryPath,
        string GameIniPath);

    public sealed class BuildResult
    {
        public bool Succeeded { get; init; }
        public string Error { get; init; } = "";
        public PluginLayout? Layout { get; init; }
        public IReadOnlyList<RegistryRow> Rows { get; init; } = Array.Empty<RegistryRow>();
        public string VerificationLine { get; init; } = "";
    }

    public static PluginLayout CreateLayout(string buildRoot, string modId)
    {
        var pluginName = $"{modId}Registry";
        var directory = Path.Combine(buildRoot, "Engine", "Plugins", "Mods", pluginName);
        return new PluginLayout(
            pluginName,
            directory,
            Path.Combine(directory, pluginName + ".uplugin"),
            Path.Combine(directory, "AssetRegistry.bin"),
            Path.Combine(directory, "Config", "Game.ini"));
    }

    /// <summary>Rejects malformed package paths and duplicate primary asset IDs before UE runs.</summary>
    public static List<string> ValidateRows(IEnumerable<RegistryRow> candidates)
    {
        var errors = new List<string>();
        var packages = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var primaryNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var raw in candidates)
        {
            var package = UnrealPathUtil.NormalizePackagePath(raw.PackagePath);
            if (string.IsNullOrWhiteSpace(package) || !package.StartsWith("/Game/Mods/", StringComparison.OrdinalIgnoreCase))
            {
                errors.Add($"Registry DCMD must be a clean /Game/Mods package path: '{raw.PackagePath}'.");
                continue;
            }
            if (!packages.Add(package))
            {
                errors.Add($"Registry contains the DCMD package twice: '{package}'.");
            }

            var asset = UnrealPathUtil.AssetName(package);
            if (string.IsNullOrWhiteSpace(asset) || !primaryNames.Add(asset))
            {
                errors.Add($"Registry primary asset name collides: '{asset}'. DCMD names must be unique within a mod.");
            }
        }

        if (packages.Count == 0)
        {
            errors.Add("Registry has no enabled suit DCMD rows.");
        }
        return errors;
    }

    public static string BuildDescriptorJson(string pluginName, string modDisplayName)
    {
        var descriptor = new
        {
            FileVersion = 3,
            Version = 1,
            VersionName = "1.0",
            FriendlyName = $"{modDisplayName} Registry",
            Description = "Cooked PawnMetaData Asset Registry rows generated by Batcomputer.",
            Category = "Mods",
            CanContainContent = true,
            NoCode = true,
            EnabledByDefault = true,
            ExplicitlyLoaded = false,
            Installed = true,
            IsBetaVersion = false,
            SupportedTargetPlatforms = new[] { "Win64" },
            Modules = Array.Empty<object>(),
        };
        return JsonSerializer.Serialize(descriptor, new JsonSerializerOptions { WriteIndented = true });
    }

    /// <summary>
    /// Extends the game's existing PawnMetaData scan rule to /Game/Mods.  This is
    /// deliberately the same remove/add pair proven by SuitSlotsRegistryProof:
    /// AssetRegistry.bin makes the rows discoverable at startup, while this rule
    /// tells the runtime AssetManager that mod-mounted DCMD packages are valid
    /// PawnMetaData scan candidates.
    /// </summary>
    public static string BuildGameIni() =>
        "[/Script/Engine.AssetManagerSettings]" + Environment.NewLine +
        "-PrimaryAssetTypesToScan=(PrimaryAssetType=\"PawnMetaData\",AssetBaseClass=\"/Script/TtPawnMetaData.TtPawnMetaData\",bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path=\"/Game/Characters\"),(Path=\"/Game/PlaceHolder/Characters\"),(Path=\"/Game/Developers\"),(Path=\"/Game/Vehicles\"),(Path=\"/Game/AdditionalContent\")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook))" + Environment.NewLine +
        "+PrimaryAssetTypesToScan=(PrimaryAssetType=\"PawnMetaData\",AssetBaseClass=\"/Script/TtPawnMetaData.TtPawnMetaData\",bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path=\"/Game/Characters\"),(Path=\"/Game/PlaceHolder/Characters\"),(Path=\"/Game/Developers\"),(Path=\"/Game/Vehicles\"),(Path=\"/Game/AdditionalContent\"),(Path=\"/Game/Mods\")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook))" + Environment.NewLine;

    public async Task<BuildResult> BuildAsync(
        string buildRoot,
        string modId,
        string modDisplayName,
        IEnumerable<RegistryRow> candidateRows,
        Action<string> log)
    {
        var rows = candidateRows
            .Select(row => new RegistryRow(UnrealPathUtil.NormalizePackagePath(row.PackagePath)))
            .ToList();
        var errors = ValidateRows(rows);
        if (errors.Count > 0)
        {
            return new BuildResult { Error = string.Join(" ", errors), Rows = rows };
        }

        var engineRoot = AppSettings.Current.EffectiveUnrealEngineRoot();
        var writerProject = AppSettings.Current.EffectiveRegistryWriterProjectPath();
        var buildScript = Path.Combine(engineRoot, "Engine", "Build", "BatchFiles", "Build.bat");
        var editorCommand = Path.Combine(engineRoot, "Engine", "Binaries", "Win64", "UnrealEditor-Cmd.exe");
        if (!File.Exists(buildScript) || !File.Exists(editorCommand) || !File.Exists(writerProject))
        {
            return new BuildResult
            {
                Error = "Static Asset Registry generation needs Unreal Engine 5.6 and SuitSlotsRegistryWriter. " +
                        "Open Settings and set the UE 5.6 folder plus the writer .uproject path.",
                Rows = rows,
            };
        }

        var layout = CreateLayout(buildRoot, modId);
        try
        {
            Directory.CreateDirectory(layout.PluginDirectory);
            File.WriteAllText(layout.DescriptorPath, BuildDescriptorJson(layout.PluginName, modDisplayName));
            Directory.CreateDirectory(Path.GetDirectoryName(layout.GameIniPath)!);
            File.WriteAllText(layout.GameIniPath, BuildGameIni());
            if (File.Exists(layout.RegistryPath))
            {
                File.Delete(layout.RegistryPath);
            }

            log("Building the UE 5.6 Asset Registry writer...");
            var writerBuild = await RunProcessAsync(
                Environment.GetEnvironmentVariable("ComSpec") ?? "cmd.exe",
                Path.GetDirectoryName(buildScript) ?? engineRoot,
                new[]
                {
                    "/c", buildScript,
                    "SuitSlotsRegistryWriterEditor", "Win64", "Development",
                    $"-Project={writerProject}", "-WaitMutex", "-NoHotReloadFromIDE",
                },
                log);
            if (writerBuild.ExitCode != 0)
            {
                return new BuildResult
                {
                    Error = $"The Asset Registry writer build failed (exit {writerBuild.ExitCode}).",
                    Layout = layout,
                    Rows = rows,
                };
            }

            var first = rows[0];
            var arguments = new List<string>
            {
                writerProject,
                "-run=SuitSlotsRegistryWriter",
                $"-Output={layout.RegistryPath}",
                $"-Package={first.PackagePath}",
                $"-Class={PawnMetadataClass}",
                $"-PrimaryAssetType={PrimaryAssetType}",
                $"-PrimaryAssetName={first.AssetName}",
            };
            if (rows.Count > 1)
            {
                arguments.Add("-AdditionalRows=" + string.Join(";", rows.Skip(1).Select(row => $"{row.PackagePath}|{row.AssetName}")));
            }
            // Match the proven Engine-plugin registry recipe exactly. This deliberately
            // unbacked row is harmless to the PawnMetaData scan, but proves that the
            // complete cooked plugin registry state survives shipping startup instead
            // of only seeing the mounted physical DCMD packages.
            arguments.Add($"-SentinelPackage={ProofSentinelRoot}/{layout.PluginName}Sentinel");
            arguments.AddRange(new[] { "-Unattended", "-NoSplash", "-NoSourceControl", "-UTF8Output" });

            log($"Writing and verifying {rows.Count} PawnMetaData registry row(s)...");
            var writerRun = await RunProcessAsync(
                editorCommand,
                Path.GetDirectoryName(writerProject) ?? engineRoot,
                arguments,
                log);
            var verification = writerRun.Output
                .Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries)
                .LastOrDefault(line => line.Contains(WriterResultMarker, StringComparison.Ordinal)) ?? "";
            if (writerRun.ExitCode != 0 || !File.Exists(layout.RegistryPath) || !File.Exists(layout.GameIniPath))
            {
                return new BuildResult
                {
                    Error = writerRun.ExitCode != 0
                        ? $"The Asset Registry writer failed verification (exit {writerRun.ExitCode})."
                        : "The Asset Registry release is missing AssetRegistry.bin or Config\\Game.ini.",
                    Layout = layout,
                    Rows = rows,
                    VerificationLine = verification,
                };
            }
            if (!VerificationMatches(verification, rows.Count))
            {
                return new BuildResult
                {
                    Error = "The Asset Registry writer did not report every expected PawnMetaData row as verified.",
                    Layout = layout,
                    Rows = rows,
                    VerificationLine = verification,
                };
            }

            return new BuildResult
            {
                Succeeded = true,
                Layout = layout,
                Rows = rows,
                VerificationLine = verification,
            };
        }
        catch (Exception ex)
        {
            return new BuildResult { Error = ex.Message, Layout = layout, Rows = rows };
        }
    }

    public static bool VerificationMatches(string verificationLine, int expectedRows) =>
        verificationLine.Contains(WriterResultMarker, StringComparison.Ordinal) &&
        verificationLine.Contains("cooked_header=yes", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains($"expected_primary_rows={expectedRows}", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains($"exact_primary_rows={expectedRows}", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains($"exact_primary_ids={expectedRows}", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains("all_expected_rows=yes", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains("all_expected_primary_ids=yes", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains("sentinel_enabled=yes", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains("sentinel_exact_row=yes", StringComparison.OrdinalIgnoreCase) &&
        verificationLine.Contains("sentinel_exact_primary_id=yes", StringComparison.OrdinalIgnoreCase);

    private static async Task<(int ExitCode, string Output)> RunProcessAsync(
        string fileName,
        string workingDirectory,
        IEnumerable<string> arguments,
        Action<string> log)
    {
        var psi = new ProcessStartInfo
        {
            FileName = fileName,
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        foreach (var argument in arguments)
        {
            psi.ArgumentList.Add(argument);
        }

        using var process = Process.Start(psi);
        if (process is null)
        {
            return (-1, "Could not start the Asset Registry writer process.");
        }
        var outputTask = process.StandardOutput.ReadToEndAsync();
        var errorTask = process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();
        var output = await outputTask;
        var error = await errorTask;
        if (!string.IsNullOrWhiteSpace(output)) log(output.Trim());
        if (!string.IsNullOrWhiteSpace(error)) log(error.Trim());
        return (process.ExitCode, output + Environment.NewLine + error);
    }
}
